---
name: Notion Exporter
description: |
  This action exports document data from Notion and create a pull
  request with the data in a markdown file. It will check if the
  document has been update and create a new PR with the updated
  data.
inputs:
  github-token:
    description: 'GitHub token to create pull request'
    required: true
  notion-token:
    description: 'Notion token to access the API'
    required: true
  notion-page-id:
    description: 'Notion page id to export data from'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
