---
name: Build and deploy NextJs site to AWS S3

# yamllint disable
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: 'src'

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.path }}

      - name: Build the Next.js site
        run: npm run build
        working-directory: ${{ inputs.path }}

      - name: Export static site
        run: npm run export
        working-directory: ${{ inputs.path }}

      # v4 through error "Artifact could not be deployed."
      # https://stackoverflow.com/questions/79410241/error-artifact-could-not-be-deployed-please-ensure-the-content-does-not-contai
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ inputs.path }}/out/**
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
